// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArtistEnrichmentBatch = `-- name: GetArtistEnrichmentBatch :many
SELECT
    a.id           AS artist_id,
    a.display_name,
    a.mbid,
    a.disambiguation,
    a.status       AS artist_status,
    i.status       AS image_status,
    i.url          AS image_url,
    i.width        AS image_width,
    i.height       AS image_height,
    i.credit       AS image_credit,
    b.status       AS bio_status,
    b.bio_md,
    b.sources      AS bio_sources,
    t.status       AS tour_status,
    t.tour_name,
    t.songs,
    t.observed_date,
    t.observed_venue,
    t.observed_city,
    t.setlist_url,
    t.blurb
FROM artists a
LEFT JOIN artist_images         i ON i.artist_id = a.id
LEFT JOIN artist_bios           b ON b.artist_id = a.id
LEFT JOIN artist_tour_snapshots t ON t.artist_id = a.id
WHERE a.id = ANY($1::uuid[])
`

type GetArtistEnrichmentBatchRow struct {
	ArtistID       pgtype.UUID `json:"artist_id"`
	DisplayName    string      `json:"display_name"`
	Mbid           *string     `json:"mbid"`
	Disambiguation *string     `json:"disambiguation"`
	ArtistStatus   string      `json:"artist_status"`
	ImageStatus    *string     `json:"image_status"`
	ImageUrl       *string     `json:"image_url"`
	ImageWidth     *int32      `json:"image_width"`
	ImageHeight    *int32      `json:"image_height"`
	ImageCredit    []byte      `json:"image_credit"`
	BioStatus      *string     `json:"bio_status"`
	BioMd          *string     `json:"bio_md"`
	BioSources     []byte      `json:"bio_sources"`
	TourStatus     *string     `json:"tour_status"`
	TourName       *string     `json:"tour_name"`
	Songs          []byte      `json:"songs"`
	ObservedDate   pgtype.Date `json:"observed_date"`
	ObservedVenue  *string     `json:"observed_venue"`
	ObservedCity   *string     `json:"observed_city"`
	SetlistUrl     *string     `json:"setlist_url"`
	Blurb          *string     `json:"blurb"`
}

// One row per artist id, with whatever enrichment exists. Left joins throughout
// so a resolved artist with no successful enrichment still comes back. Mirrors
// ListEventPerformersBatch's shape: the calendar handlers fetch a page, then
// batch-load the page's artists in one round trip.
func (q *Queries) GetArtistEnrichmentBatch(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetArtistEnrichmentBatchRow, error) {
	rows, err := q.db.Query(ctx, getArtistEnrichmentBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArtistEnrichmentBatchRow{}
	for rows.Next() {
		var i GetArtistEnrichmentBatchRow
		if err := rows.Scan(
			&i.ArtistID,
			&i.DisplayName,
			&i.Mbid,
			&i.Disambiguation,
			&i.ArtistStatus,
			&i.ImageStatus,
			&i.ImageUrl,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.ImageCredit,
			&i.BioStatus,
			&i.BioMd,
			&i.BioSources,
			&i.TourStatus,
			&i.TourName,
			&i.Songs,
			&i.ObservedDate,
			&i.ObservedVenue,
			&i.ObservedCity,
			&i.SetlistUrl,
			&i.Blurb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtist = `-- name: UpsertArtist :one
INSERT INTO artists (
    name_key, display_name, mbid, disambiguation, artist_type,
    country, begin_year, status, resolved_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (name_key) DO UPDATE SET
    display_name   = EXCLUDED.display_name,
    mbid           = EXCLUDED.mbid,
    disambiguation = EXCLUDED.disambiguation,
    artist_type    = EXCLUDED.artist_type,
    country        = EXCLUDED.country,
    begin_year     = EXCLUDED.begin_year,
    status         = EXCLUDED.status,
    resolved_at    = NOW(),
    updated_at     = NOW()
RETURNING id
`

type UpsertArtistParams struct {
	NameKey        string  `json:"name_key"`
	DisplayName    string  `json:"display_name"`
	Mbid           *string `json:"mbid"`
	Disambiguation *string `json:"disambiguation"`
	ArtistType     *string `json:"artist_type"`
	Country        *string `json:"country"`
	BeginYear      *string `json:"begin_year"`
	Status         string  `json:"status"`
}

func (q *Queries) UpsertArtist(ctx context.Context, arg UpsertArtistParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertArtist,
		arg.NameKey,
		arg.DisplayName,
		arg.Mbid,
		arg.Disambiguation,
		arg.ArtistType,
		arg.Country,
		arg.BeginYear,
		arg.Status,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertArtistBio = `-- name: UpsertArtistBio :exec
INSERT INTO artist_bios (
    artist_id, status, bio_md, sources, model, reason, generated_at
)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (artist_id) DO UPDATE SET
    status       = EXCLUDED.status,
    bio_md       = EXCLUDED.bio_md,
    sources      = EXCLUDED.sources,
    model        = EXCLUDED.model,
    reason       = EXCLUDED.reason,
    generated_at = NOW()
`

type UpsertArtistBioParams struct {
	ArtistID pgtype.UUID `json:"artist_id"`
	Status   string      `json:"status"`
	BioMd    *string     `json:"bio_md"`
	Sources  []byte      `json:"sources"`
	Model    *string     `json:"model"`
	Reason   *string     `json:"reason"`
}

func (q *Queries) UpsertArtistBio(ctx context.Context, arg UpsertArtistBioParams) error {
	_, err := q.db.Exec(ctx, upsertArtistBio,
		arg.ArtistID,
		arg.Status,
		arg.BioMd,
		arg.Sources,
		arg.Model,
		arg.Reason,
	)
	return err
}

const upsertArtistImage = `-- name: UpsertArtistImage :exec
INSERT INTO artist_images (
    artist_id, status, url, width, height, file, source, credit, reason, checked_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
ON CONFLICT (artist_id) DO UPDATE SET
    status     = EXCLUDED.status,
    url        = EXCLUDED.url,
    width      = EXCLUDED.width,
    height     = EXCLUDED.height,
    file       = EXCLUDED.file,
    source     = EXCLUDED.source,
    credit     = EXCLUDED.credit,
    reason     = EXCLUDED.reason,
    checked_at = NOW()
`

type UpsertArtistImageParams struct {
	ArtistID pgtype.UUID `json:"artist_id"`
	Status   string      `json:"status"`
	Url      *string     `json:"url"`
	Width    *int32      `json:"width"`
	Height   *int32      `json:"height"`
	File     *string     `json:"file"`
	Source   *string     `json:"source"`
	Credit   []byte      `json:"credit"`
	Reason   *string     `json:"reason"`
}

func (q *Queries) UpsertArtistImage(ctx context.Context, arg UpsertArtistImageParams) error {
	_, err := q.db.Exec(ctx, upsertArtistImage,
		arg.ArtistID,
		arg.Status,
		arg.Url,
		arg.Width,
		arg.Height,
		arg.File,
		arg.Source,
		arg.Credit,
		arg.Reason,
	)
	return err
}

const upsertArtistTourSnapshot = `-- name: UpsertArtistTourSnapshot :exec
INSERT INTO artist_tour_snapshots (
    artist_id, status, tour_name, songs, observed_date, observed_venue,
    observed_city, setlist_url, blurb, blurb_model, reason, fetched_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW())
ON CONFLICT (artist_id) DO UPDATE SET
    status         = EXCLUDED.status,
    tour_name      = EXCLUDED.tour_name,
    songs          = EXCLUDED.songs,
    observed_date  = EXCLUDED.observed_date,
    observed_venue = EXCLUDED.observed_venue,
    observed_city  = EXCLUDED.observed_city,
    setlist_url    = EXCLUDED.setlist_url,
    blurb          = EXCLUDED.blurb,
    blurb_model    = EXCLUDED.blurb_model,
    reason         = EXCLUDED.reason,
    fetched_at     = NOW()
`

type UpsertArtistTourSnapshotParams struct {
	ArtistID      pgtype.UUID `json:"artist_id"`
	Status        string      `json:"status"`
	TourName      *string     `json:"tour_name"`
	Songs         []byte      `json:"songs"`
	ObservedDate  pgtype.Date `json:"observed_date"`
	ObservedVenue *string     `json:"observed_venue"`
	ObservedCity  *string     `json:"observed_city"`
	SetlistUrl    *string     `json:"setlist_url"`
	Blurb         *string     `json:"blurb"`
	BlurbModel    *string     `json:"blurb_model"`
	Reason        *string     `json:"reason"`
}

func (q *Queries) UpsertArtistTourSnapshot(ctx context.Context, arg UpsertArtistTourSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertArtistTourSnapshot,
		arg.ArtistID,
		arg.Status,
		arg.TourName,
		arg.Songs,
		arg.ObservedDate,
		arg.ObservedVenue,
		arg.ObservedCity,
		arg.SetlistUrl,
		arg.Blurb,
		arg.BlurbModel,
		arg.Reason,
	)
	return err
}
