// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artist_genre_cache.sql

package store

import (
	"context"
)

const getArtistGenreCache = `-- name: GetArtistGenreCache :one
SELECT name_key, mbid, genres, status, resolved_at
FROM artist_genre_cache
WHERE name_key = $1
`

func (q *Queries) GetArtistGenreCache(ctx context.Context, nameKey string) (ArtistGenreCache, error) {
	row := q.db.QueryRow(ctx, getArtistGenreCache, nameKey)
	var i ArtistGenreCache
	err := row.Scan(
		&i.NameKey,
		&i.Mbid,
		&i.Genres,
		&i.Status,
		&i.ResolvedAt,
	)
	return i, err
}

const upsertArtistGenreCache = `-- name: UpsertArtistGenreCache :exec
INSERT INTO artist_genre_cache (name_key, mbid, genres, status, resolved_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (name_key) DO UPDATE SET
    mbid        = EXCLUDED.mbid,
    genres      = EXCLUDED.genres,
    status      = EXCLUDED.status,
    resolved_at = NOW()
`

type UpsertArtistGenreCacheParams struct {
	NameKey string  `json:"name_key"`
	Mbid    *string `json:"mbid"`
	Genres  []byte  `json:"genres"`
	Status  string  `json:"status"`
}

func (q *Queries) UpsertArtistGenreCache(ctx context.Context, arg UpsertArtistGenreCacheParams) error {
	_, err := q.db.Exec(ctx, upsertArtistGenreCache,
		arg.NameKey,
		arg.Mbid,
		arg.Genres,
		arg.Status,
	)
	return err
}
