// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMatchedEventForUser = `-- name: GetMatchedEventForUser :one
SELECT
    e.id              AS event_id,
    e.title,
    e.description,
    e.starts_at,
    e.ends_at,
    e.image_url,
    e.url,
    v.name            AS venue_name,
    v.address         AS venue_address,
    m.score,
    m.score_breakdown
FROM events e
JOIN venues v ON v.id = e.venue_id
LEFT JOIN user_event_match m ON m.event_id = e.id AND m.user_id = $2
WHERE e.id = $1
  AND e.archived_at IS NULL
`

type GetMatchedEventForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetMatchedEventForUserRow struct {
	EventID        pgtype.UUID        `json:"event_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	ImageUrl       *string            `json:"image_url"`
	Url            *string            `json:"url"`
	VenueName      string             `json:"venue_name"`
	VenueAddress   *string            `json:"venue_address"`
	Score          *float64           `json:"score"`
	ScoreBreakdown []byte             `json:"score_breakdown"`
}

func (q *Queries) GetMatchedEventForUser(ctx context.Context, arg GetMatchedEventForUserParams) (GetMatchedEventForUserRow, error) {
	row := q.db.QueryRow(ctx, getMatchedEventForUser, arg.ID, arg.UserID)
	var i GetMatchedEventForUserRow
	err := row.Scan(
		&i.EventID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.ImageUrl,
		&i.Url,
		&i.VenueName,
		&i.VenueAddress,
		&i.Score,
		&i.ScoreBreakdown,
	)
	return i, err
}

const getUserCalendarInRange = `-- name: GetUserCalendarInRange :many
SELECT
    e.id              AS event_id,
    e.title,
    e.description,
    e.starts_at,
    e.ends_at,
    e.image_url,
    e.url,
    v.name            AS venue_name,
    v.address         AS venue_address,
    m.score,
    m.score_breakdown
FROM user_event_match m
JOIN events e ON e.id = m.event_id
JOIN venues v ON v.id = e.venue_id
WHERE m.user_id = $1
  AND e.archived_at IS NULL
  AND e.starts_at >= $2
  AND e.starts_at <  $3
ORDER BY e.starts_at ASC
`

type GetUserCalendarInRangeParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
	StartsAt_2 pgtype.Timestamptz `json:"starts_at_2"`
}

type GetUserCalendarInRangeRow struct {
	EventID        pgtype.UUID        `json:"event_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	ImageUrl       *string            `json:"image_url"`
	Url            *string            `json:"url"`
	VenueName      string             `json:"venue_name"`
	VenueAddress   *string            `json:"venue_address"`
	Score          float64            `json:"score"`
	ScoreBreakdown []byte             `json:"score_breakdown"`
}

func (q *Queries) GetUserCalendarInRange(ctx context.Context, arg GetUserCalendarInRangeParams) ([]GetUserCalendarInRangeRow, error) {
	rows, err := q.db.Query(ctx, getUserCalendarInRange, arg.UserID, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserCalendarInRangeRow{}
	for rows.Next() {
		var i GetUserCalendarInRangeRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.ImageUrl,
			&i.Url,
			&i.VenueName,
			&i.VenueAddress,
			&i.Score,
			&i.ScoreBreakdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
