// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_confirmations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailConfirmation = `-- name: ConsumeEmailConfirmation :exec
UPDATE email_confirmations
SET consumed_at = NOW()
WHERE user_id = $1
`

func (q *Queries) ConsumeEmailConfirmation(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, consumeEmailConfirmation, userID)
	return err
}

const getEmailConfirmationByHash = `-- name: GetEmailConfirmationByHash :one
SELECT user_id, token_hash, expires_at, consumed_at, created_at
FROM email_confirmations
WHERE token_hash = $1
`

func (q *Queries) GetEmailConfirmationByHash(ctx context.Context, tokenHash []byte) (EmailConfirmation, error) {
	row := q.db.QueryRow(ctx, getEmailConfirmationByHash, tokenHash)
	var i EmailConfirmation
	err := row.Scan(
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertEmailConfirmation = `-- name: UpsertEmailConfirmation :exec
INSERT INTO email_confirmations (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET
    token_hash  = EXCLUDED.token_hash,
    expires_at  = EXCLUDED.expires_at,
    consumed_at = NULL,
    created_at  = NOW()
`

type UpsertEmailConfirmationParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertEmailConfirmation(ctx context.Context, arg UpsertEmailConfirmationParams) error {
	_, err := q.db.Exec(ctx, upsertEmailConfirmation, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}
