// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_sources.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventSourceByName = `-- name: GetEventSourceByName :one
SELECT id, name, adapter_kind, config
FROM event_sources
WHERE name = $1
`

type GetEventSourceByNameRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	AdapterKind string      `json:"adapter_kind"`
	Config      []byte      `json:"config"`
}

func (q *Queries) GetEventSourceByName(ctx context.Context, name string) (GetEventSourceByNameRow, error) {
	row := q.db.QueryRow(ctx, getEventSourceByName, name)
	var i GetEventSourceByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdapterKind,
		&i.Config,
	)
	return i, err
}
