// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_associations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEventGenresByEvent = `-- name: DeleteEventGenresByEvent :exec
DELETE FROM event_genres WHERE event_id = $1
`

func (q *Queries) DeleteEventGenresByEvent(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventGenresByEvent, eventID)
	return err
}

const deleteEventPerformersByEvent = `-- name: DeleteEventPerformersByEvent :exec
DELETE FROM event_performers WHERE event_id = $1
`

func (q *Queries) DeleteEventPerformersByEvent(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventPerformersByEvent, eventID)
	return err
}

const insertEventGenre = `-- name: InsertEventGenre :exec
INSERT INTO event_genres (event_id, genre_slug)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertEventGenreParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	GenreSlug string      `json:"genre_slug"`
}

func (q *Queries) InsertEventGenre(ctx context.Context, arg InsertEventGenreParams) error {
	_, err := q.db.Exec(ctx, insertEventGenre, arg.EventID, arg.GenreSlug)
	return err
}

const insertEventPerformer = `-- name: InsertEventPerformer :exec
INSERT INTO event_performers (event_id, performer_name, normalized_name)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, normalized_name) DO NOTHING
`

type InsertEventPerformerParams struct {
	EventID        pgtype.UUID `json:"event_id"`
	PerformerName  string      `json:"performer_name"`
	NormalizedName string      `json:"normalized_name"`
}

func (q *Queries) InsertEventPerformer(ctx context.Context, arg InsertEventPerformerParams) error {
	_, err := q.db.Exec(ctx, insertEventPerformer, arg.EventID, arg.PerformerName, arg.NormalizedName)
	return err
}

const listEventGenresByEvent = `-- name: ListEventGenresByEvent :many
SELECT genre_slug FROM event_genres WHERE event_id = $1 ORDER BY genre_slug ASC
`

func (q *Queries) ListEventGenresByEvent(ctx context.Context, eventID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listEventGenresByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var genre_slug string
		if err := rows.Scan(&genre_slug); err != nil {
			return nil, err
		}
		items = append(items, genre_slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventPerformersByEvent = `-- name: ListEventPerformersByEvent :many
SELECT performer_name, normalized_name
FROM event_performers
WHERE event_id = $1
ORDER BY performer_name ASC
`

type ListEventPerformersByEventRow struct {
	PerformerName  string `json:"performer_name"`
	NormalizedName string `json:"normalized_name"`
}

func (q *Queries) ListEventPerformersByEvent(ctx context.Context, eventID pgtype.UUID) ([]ListEventPerformersByEventRow, error) {
	rows, err := q.db.Query(ctx, listEventPerformersByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventPerformersByEventRow{}
	for rows.Next() {
		var i ListEventPerformersByEventRow
		if err := rows.Scan(&i.PerformerName, &i.NormalizedName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
