// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_not_interested.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addNotInterested = `-- name: AddNotInterested :exec
INSERT INTO user_event_not_interested (user_id, event_id)
VALUES ($1, $2)
ON CONFLICT (user_id, event_id) DO NOTHING
`

type AddNotInterestedParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	EventID pgtype.UUID `json:"event_id"`
}

func (q *Queries) AddNotInterested(ctx context.Context, arg AddNotInterestedParams) error {
	_, err := q.db.Exec(ctx, addNotInterested, arg.UserID, arg.EventID)
	return err
}

const clearNotInterested = `-- name: ClearNotInterested :exec
DELETE FROM user_event_not_interested
WHERE user_id = $1
`

func (q *Queries) ClearNotInterested(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearNotInterested, userID)
	return err
}
