// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventByID = `-- name: GetEventByID :one
SELECT id, source_id, source_event_id, title, description, starts_at, ends_at,
       venue_id, image_url, url, last_seen_at, archived_at, created_at, updated_at
FROM events
WHERE id = $1
`

type GetEventByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	SourceID      pgtype.UUID        `json:"source_id"`
	SourceEventID string             `json:"source_event_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	VenueID       pgtype.UUID        `json:"venue_id"`
	ImageUrl      *string            `json:"image_url"`
	Url           *string            `json:"url"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceEventID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.VenueID,
		&i.ImageUrl,
		&i.Url,
		&i.LastSeenAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventBySourceKey = `-- name: GetEventBySourceKey :one
SELECT id, source_id, source_event_id, title, description, starts_at, ends_at,
       venue_id, image_url, url, last_seen_at, archived_at, created_at, updated_at
FROM events
WHERE source_id = $1 AND source_event_id = $2
`

type GetEventBySourceKeyParams struct {
	SourceID      pgtype.UUID `json:"source_id"`
	SourceEventID string      `json:"source_event_id"`
}

type GetEventBySourceKeyRow struct {
	ID            pgtype.UUID        `json:"id"`
	SourceID      pgtype.UUID        `json:"source_id"`
	SourceEventID string             `json:"source_event_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	VenueID       pgtype.UUID        `json:"venue_id"`
	ImageUrl      *string            `json:"image_url"`
	Url           *string            `json:"url"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEventBySourceKey(ctx context.Context, arg GetEventBySourceKeyParams) (GetEventBySourceKeyRow, error) {
	row := q.db.QueryRow(ctx, getEventBySourceKey, arg.SourceID, arg.SourceEventID)
	var i GetEventBySourceKeyRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceEventID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.VenueID,
		&i.ImageUrl,
		&i.Url,
		&i.LastSeenAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEvent = `-- name: UpsertEvent :one
INSERT INTO events (
    source_id, source_event_id, title, description, starts_at, ends_at,
    venue_id, image_url, url, last_seen_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
ON CONFLICT (source_id, source_event_id)
DO UPDATE SET
    title         = EXCLUDED.title,
    description   = EXCLUDED.description,
    starts_at     = EXCLUDED.starts_at,
    ends_at       = EXCLUDED.ends_at,
    venue_id      = EXCLUDED.venue_id,
    image_url     = EXCLUDED.image_url,
    url           = EXCLUDED.url,
    last_seen_at  = NOW(),
    archived_at   = NULL,
    updated_at    = NOW()
RETURNING id
`

type UpsertEventParams struct {
	SourceID      pgtype.UUID        `json:"source_id"`
	SourceEventID string             `json:"source_event_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	VenueID       pgtype.UUID        `json:"venue_id"`
	ImageUrl      *string            `json:"image_url"`
	Url           *string            `json:"url"`
}

func (q *Queries) UpsertEvent(ctx context.Context, arg UpsertEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertEvent,
		arg.SourceID,
		arg.SourceEventID,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.VenueID,
		arg.ImageUrl,
		arg.Url,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
