// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_going.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGoing = `-- name: AddGoing :exec
INSERT INTO user_event_going (user_id, event_id)
VALUES ($1, $2)
ON CONFLICT (user_id, event_id) DO NOTHING
`

type AddGoingParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	EventID pgtype.UUID `json:"event_id"`
}

func (q *Queries) AddGoing(ctx context.Context, arg AddGoingParams) error {
	_, err := q.db.Exec(ctx, addGoing, arg.UserID, arg.EventID)
	return err
}

const clearGoing = `-- name: ClearGoing :exec
DELETE FROM user_event_going
WHERE user_id = $1 AND event_id = $2
`

type ClearGoingParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	EventID pgtype.UUID `json:"event_id"`
}

func (q *Queries) ClearGoing(ctx context.Context, arg ClearGoingParams) error {
	_, err := q.db.Exec(ctx, clearGoing, arg.UserID, arg.EventID)
	return err
}

const listGoing = `-- name: ListGoing :many
SELECT event_id
FROM user_event_going
WHERE user_id = $1
`

func (q *Queries) ListGoing(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listGoing, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var event_id pgtype.UUID
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoingEvents = `-- name: ListGoingEvents :many
SELECT
    e.id              AS event_id,
    e.title,
    e.description,
    e.starts_at,
    e.ends_at,
    e.image_url,
    e.url,
    e.segment,
    e.headline_artist_id,
    v.name            AS venue_name,
    v.address         AS venue_address,
    m.score,
    m.score_breakdown
FROM user_event_going g
JOIN events e ON e.id = g.event_id
JOIN venues v ON v.id = e.venue_id
LEFT JOIN user_event_match m ON m.event_id = e.id AND m.user_id = g.user_id
WHERE g.user_id = $1
  AND e.archived_at IS NULL
ORDER BY e.starts_at ASC, e.id ASC
`

type ListGoingEventsRow struct {
	EventID          pgtype.UUID        `json:"event_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	ImageUrl         *string            `json:"image_url"`
	Url              *string            `json:"url"`
	Segment          *string            `json:"segment"`
	HeadlineArtistID pgtype.UUID        `json:"headline_artist_id"`
	VenueName        string             `json:"venue_name"`
	VenueAddress     *string            `json:"venue_address"`
	Score            *float64           `json:"score"`
	ScoreBreakdown   []byte             `json:"score_breakdown"`
}

// Every event the user has marked going, in full calendar-row shape. Past and
// future alike: the client splits the list on the event's own start time, so a
// time filter here would cost it the "went" half. LEFT JOIN on the match so an
// event marked going from the all-city calendar -- which matches nothing -- is
// still returned, with a NULL score.
// id breaks the tie so events starting at the same instant keep a stable order.
func (q *Queries) ListGoingEvents(ctx context.Context, userID pgtype.UUID) ([]ListGoingEventsRow, error) {
	rows, err := q.db.Query(ctx, listGoingEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoingEventsRow{}
	for rows.Next() {
		var i ListGoingEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.ImageUrl,
			&i.Url,
			&i.Segment,
			&i.HeadlineArtistID,
			&i.VenueName,
			&i.VenueAddress,
			&i.Score,
			&i.ScoreBreakdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
