// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: genres.sql

package store

import (
	"context"
)

const genreExists = `-- name: GenreExists :one
SELECT EXISTS (SELECT 1 FROM genres WHERE slug = $1) AS exists
`

func (q *Queries) GenreExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, genreExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGenres = `-- name: ListGenres :many
SELECT slug, label FROM genres ORDER BY label ASC
`

func (q *Queries) ListGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.Query(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Genre{}
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.Slug, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
