// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ical_tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIcalTokenByUser = `-- name: DeleteIcalTokenByUser :exec
DELETE FROM ical_tokens WHERE user_id = $1
`

func (q *Queries) DeleteIcalTokenByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIcalTokenByUser, userID)
	return err
}

const getIcalTokenByHash = `-- name: GetIcalTokenByHash :one
SELECT user_id, token_hash, created_at, last_accessed_at
FROM ical_tokens
WHERE token_hash = $1
`

func (q *Queries) GetIcalTokenByHash(ctx context.Context, tokenHash []byte) (IcalToken, error) {
	row := q.db.QueryRow(ctx, getIcalTokenByHash, tokenHash)
	var i IcalToken
	err := row.Scan(
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const updateIcalTokenLastAccessed = `-- name: UpdateIcalTokenLastAccessed :exec
UPDATE ical_tokens SET last_accessed_at = NOW() WHERE user_id = $1
`

func (q *Queries) UpdateIcalTokenLastAccessed(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateIcalTokenLastAccessed, userID)
	return err
}

const upsertIcalToken = `-- name: UpsertIcalToken :exec
INSERT INTO ical_tokens (user_id, token_hash)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET
    token_hash       = EXCLUDED.token_hash,
    created_at       = NOW(),
    last_accessed_at = NULL
`

type UpsertIcalTokenParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	TokenHash []byte      `json:"token_hash"`
}

func (q *Queries) UpsertIcalToken(ctx context.Context, arg UpsertIcalTokenParams) error {
	_, err := q.db.Exec(ctx, upsertIcalToken, arg.UserID, arg.TokenHash)
	return err
}
