// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manual_added_going_events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createManualAddedGoingEvent = `-- name: CreateManualAddedGoingEvent :one
INSERT INTO user_manual_added_going_events (user_id, show_date, event_name, venue_name)
VALUES ($1, $2, $3, $4)
RETURNING id, show_date, event_name, venue_name, created_at
`

type CreateManualAddedGoingEventParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ShowDate  pgtype.Date `json:"show_date"`
	EventName string      `json:"event_name"`
	VenueName string      `json:"venue_name"`
}

type CreateManualAddedGoingEventRow struct {
	ID        pgtype.UUID        `json:"id"`
	ShowDate  pgtype.Date        `json:"show_date"`
	EventName string             `json:"event_name"`
	VenueName string             `json:"venue_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateManualAddedGoingEvent(ctx context.Context, arg CreateManualAddedGoingEventParams) (CreateManualAddedGoingEventRow, error) {
	row := q.db.QueryRow(ctx, createManualAddedGoingEvent,
		arg.UserID,
		arg.ShowDate,
		arg.EventName,
		arg.VenueName,
	)
	var i CreateManualAddedGoingEventRow
	err := row.Scan(
		&i.ID,
		&i.ShowDate,
		&i.EventName,
		&i.VenueName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteManualAddedGoingEventForUser = `-- name: DeleteManualAddedGoingEventForUser :exec
DELETE FROM user_manual_added_going_events
WHERE id = $1 AND user_id = $2
`

type DeleteManualAddedGoingEventForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Scoped by user for the same reason as the update above. Idempotent: deleting
// an unknown or someone else's id affects no rows and is not an error.
func (q *Queries) DeleteManualAddedGoingEventForUser(ctx context.Context, arg DeleteManualAddedGoingEventForUserParams) error {
	_, err := q.db.Exec(ctx, deleteManualAddedGoingEventForUser, arg.ID, arg.UserID)
	return err
}

const listManualAddedGoingEventsByUser = `-- name: ListManualAddedGoingEventsByUser :many
SELECT id, show_date, event_name, venue_name, created_at
FROM user_manual_added_going_events
WHERE user_id = $1
ORDER BY show_date DESC, id ASC
`

type ListManualAddedGoingEventsByUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	ShowDate  pgtype.Date        `json:"show_date"`
	EventName string             `json:"event_name"`
	VenueName string             `json:"venue_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Newest show first. The client re-sorts anyway once these are merged with the
// real going events, but a stable server order keeps the list from shuffling
// between fetches. id breaks the tie so two shows on the same day hold still.
func (q *Queries) ListManualAddedGoingEventsByUser(ctx context.Context, userID pgtype.UUID) ([]ListManualAddedGoingEventsByUserRow, error) {
	rows, err := q.db.Query(ctx, listManualAddedGoingEventsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManualAddedGoingEventsByUserRow{}
	for rows.Next() {
		var i ListManualAddedGoingEventsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ShowDate,
			&i.EventName,
			&i.VenueName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateManualAddedGoingEventForUser = `-- name: UpdateManualAddedGoingEventForUser :one
UPDATE user_manual_added_going_events
SET show_date  = $3,
    event_name = $4,
    venue_name = $5,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, show_date, event_name, venue_name, created_at
`

type UpdateManualAddedGoingEventForUserParams struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	ShowDate  pgtype.Date `json:"show_date"`
	EventName string      `json:"event_name"`
	VenueName string      `json:"venue_name"`
}

type UpdateManualAddedGoingEventForUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	ShowDate  pgtype.Date        `json:"show_date"`
	EventName string             `json:"event_name"`
	VenueName string             `json:"venue_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// user_id in the WHERE, not just the id: without it any confirmed user could
// rewrite any other user's row by guessing a uuid. No row returned means the
// id is unknown OR belongs to someone else, and the handler answers 404 to
// both so the endpoint never confirms that a stranger's id exists.
func (q *Queries) UpdateManualAddedGoingEventForUser(ctx context.Context, arg UpdateManualAddedGoingEventForUserParams) (UpdateManualAddedGoingEventForUserRow, error) {
	row := q.db.QueryRow(ctx, updateManualAddedGoingEventForUser,
		arg.ID,
		arg.UserID,
		arg.ShowDate,
		arg.EventName,
		arg.VenueName,
	)
	var i UpdateManualAddedGoingEventForUserRow
	err := row.Scan(
		&i.ID,
		&i.ShowDate,
		&i.EventName,
		&i.VenueName,
		&i.CreatedAt,
	)
	return i, err
}
