// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_config.sql

package store

import (
	"context"
)

const listMatchConfig = `-- name: ListMatchConfig :many
SELECT key, value FROM match_config ORDER BY key ASC
`

type ListMatchConfigRow struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) ListMatchConfig(ctx context.Context) ([]ListMatchConfigRow, error) {
	rows, err := q.db.Query(ctx, listMatchConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchConfigRow{}
	for rows.Next() {
		var i ListMatchConfigRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
