// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type City struct {
	ID       pgtype.UUID `json:"id"`
	Slug     string      `json:"slug"`
	Name     string      `json:"name"`
	Timezone string      `json:"timezone"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                         pgtype.UUID        `json:"id"`
	Email                      string             `json:"email"`
	PasswordHash               string             `json:"password_hash"`
	CityID                     pgtype.UUID        `json:"city_id"`
	InterestEmbedding          *pgvector.Vector   `json:"interest_embedding"`
	InterestEmbeddingUpdatedAt pgtype.Timestamptz `json:"interest_embedding_updated_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
}

type UserInterest struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Kind            string             `json:"kind"`
	Value           string             `json:"value"`
	NormalizedValue string             `json:"normalized_value"`
	Weight          float64            `json:"weight"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
