// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Artist struct {
	ID             pgtype.UUID        `json:"id"`
	NameKey        string             `json:"name_key"`
	DisplayName    string             `json:"display_name"`
	Mbid           *string            `json:"mbid"`
	Disambiguation *string            `json:"disambiguation"`
	ArtistType     *string            `json:"artist_type"`
	Country        *string            `json:"country"`
	BeginYear      *string            `json:"begin_year"`
	Status         string             `json:"status"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ArtistBio struct {
	ArtistID    pgtype.UUID        `json:"artist_id"`
	Status      string             `json:"status"`
	BioMd       *string            `json:"bio_md"`
	Sources     []byte             `json:"sources"`
	Model       *string            `json:"model"`
	Reason      *string            `json:"reason"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

type ArtistGenreCache struct {
	NameKey    string             `json:"name_key"`
	Mbid       *string            `json:"mbid"`
	Genres     []byte             `json:"genres"`
	Status     string             `json:"status"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type ArtistImage struct {
	ArtistID  pgtype.UUID        `json:"artist_id"`
	Status    string             `json:"status"`
	Url       *string            `json:"url"`
	Width     *int32             `json:"width"`
	Height    *int32             `json:"height"`
	File      *string            `json:"file"`
	Source    *string            `json:"source"`
	Credit    []byte             `json:"credit"`
	Reason    *string            `json:"reason"`
	CheckedAt pgtype.Timestamptz `json:"checked_at"`
}

type ArtistTourSnapshot struct {
	ArtistID      pgtype.UUID        `json:"artist_id"`
	Status        string             `json:"status"`
	TourName      *string            `json:"tour_name"`
	Songs         []byte             `json:"songs"`
	ObservedDate  pgtype.Date        `json:"observed_date"`
	ObservedVenue *string            `json:"observed_venue"`
	ObservedCity  *string            `json:"observed_city"`
	SetlistUrl    *string            `json:"setlist_url"`
	Blurb         *string            `json:"blurb"`
	BlurbModel    *string            `json:"blurb_model"`
	Reason        *string            `json:"reason"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
}

type City struct {
	ID       pgtype.UUID `json:"id"`
	Slug     string      `json:"slug"`
	Name     string      `json:"name"`
	Timezone string      `json:"timezone"`
}

type EmailConfirmation struct {
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID                 pgtype.UUID        `json:"id"`
	SourceID           pgtype.UUID        `json:"source_id"`
	SourceEventID      string             `json:"source_event_id"`
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	VenueID            pgtype.UUID        `json:"venue_id"`
	ImageUrl           *string            `json:"image_url"`
	Url                *string            `json:"url"`
	Embedding          *pgvector.Vector   `json:"embedding"`
	EmbeddingUpdatedAt pgtype.Timestamptz `json:"embedding_updated_at"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TimeTbd            bool               `json:"time_tbd"`
	HeadlineArtistID   pgtype.UUID        `json:"headline_artist_id"`
	Segment            *string            `json:"segment"`
}

type EventGenre struct {
	EventID   pgtype.UUID `json:"event_id"`
	GenreSlug string      `json:"genre_slug"`
}

type EventPerformer struct {
	EventID        pgtype.UUID `json:"event_id"`
	PerformerName  string      `json:"performer_name"`
	NormalizedName string      `json:"normalized_name"`
}

type EventSource struct {
	ID                     pgtype.UUID        `json:"id"`
	Name                   string             `json:"name"`
	AdapterKind            string             `json:"adapter_kind"`
	Config                 []byte             `json:"config"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	ExemptFromStaleArchive bool               `json:"exempt_from_stale_archive"`
}

type Genre struct {
	Slug  string `json:"slug"`
	Label string `json:"label"`
}

type IcalToken struct {
	UserID         pgtype.UUID        `json:"user_id"`
	TokenHash      []byte             `json:"token_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
}

type MatchConfig struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PosterJob struct {
	ID            string             `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Performer     string             `json:"performer"`
	Venue         string             `json:"venue"`
	Date          string             `json:"date"`
	Status        string             `json:"status"`
	PngKey        *string            `json:"png_key"`
	Artist        []byte             `json:"artist"`
	Credit        []byte             `json:"credit"`
	FailureStage  *string            `json:"failure_stage"`
	FailureReason *string            `json:"failure_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                         pgtype.UUID        `json:"id"`
	Email                      string             `json:"email"`
	PasswordHash               string             `json:"password_hash"`
	CityID                     pgtype.UUID        `json:"city_id"`
	InterestEmbedding          *pgvector.Vector   `json:"interest_embedding"`
	InterestEmbeddingUpdatedAt pgtype.Timestamptz `json:"interest_embedding_updated_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	ScoreThreshold             *float64           `json:"score_threshold"`
	Confirmed                  bool               `json:"confirmed"`
	ShowSetlists               bool               `json:"show_setlists"`
}

type UserEventMatch struct {
	UserID         pgtype.UUID        `json:"user_id"`
	EventID        pgtype.UUID        `json:"event_id"`
	Score          float64            `json:"score"`
	ScoreBreakdown []byte             `json:"score_breakdown"`
	ComputedAt     pgtype.Timestamptz `json:"computed_at"`
}

type UserEventNotInterested struct {
	UserID    pgtype.UUID        `json:"user_id"`
	EventID   pgtype.UUID        `json:"event_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserInterest struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Kind            string             `json:"kind"`
	Value           string             `json:"value"`
	NormalizedValue string             `json:"normalized_value"`
	Weight          float64            `json:"weight"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserSpotifyToken struct {
	UserID          pgtype.UUID        `json:"user_id"`
	AccessTokenEnc  []byte             `json:"access_token_enc"`
	RefreshTokenEnc []byte             `json:"refresh_token_enc"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Scope           string             `json:"scope"`
	LastSyncedAt    pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Venue struct {
	ID             pgtype.UUID        `json:"id"`
	CityID         pgtype.UUID        `json:"city_id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Address        *string            `json:"address"`
	Lat            *float64           `json:"lat"`
	Lng            *float64           `json:"lng"`
	WebsiteUrl     *string            `json:"website_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
