// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: poster_jobs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPosterJob = `-- name: ClaimPosterJob :one
INSERT INTO poster_jobs (id, performer, venue, date, status, updated_at)
VALUES ($1, $2, $3, $4, 'pending', NOW())
ON CONFLICT (id) DO UPDATE SET
    status         = 'pending',
    svg_key        = NULL,
    png_key        = NULL,
    artist         = NULL,
    credit         = NULL,
    failure_stage  = NULL,
    failure_reason = NULL,
    updated_at     = NOW()
WHERE poster_jobs.status = 'failed'
   OR (poster_jobs.status = 'pending' AND poster_jobs.updated_at < $5)
RETURNING id, performer, venue, date, status, svg_key, png_key, artist, credit, failure_stage, failure_reason, created_at, updated_at
`

type ClaimPosterJobParams struct {
	ID          string             `json:"id"`
	Performer   string             `json:"performer"`
	Venue       string             `json:"venue"`
	Date        string             `json:"date"`
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
}

// Claim a job for generation. Returns a row ONLY when this caller won the
// claim; sqlc surfaces "not claimed" as pgx.ErrNoRows. A job is claimable when
// it does not exist, previously failed, or is a pending row stranded by a task
// restart (nothing else would ever clear it, since the goroutine died with the
// task).
//
// The cutoff uses sqlc.arg(stale_before) rather than a positional $5: this
// statement both SETS updated_at and COMPARES it, and sqlc names positional
// params after the column they touch, so a bare $5 would collide with the
// assignment and produce a confusing generated field name.
func (q *Queries) ClaimPosterJob(ctx context.Context, arg ClaimPosterJobParams) (PosterJob, error) {
	row := q.db.QueryRow(ctx, claimPosterJob,
		arg.ID,
		arg.Performer,
		arg.Venue,
		arg.Date,
		arg.StaleBefore,
	)
	var i PosterJob
	err := row.Scan(
		&i.ID,
		&i.Performer,
		&i.Venue,
		&i.Date,
		&i.Status,
		&i.SvgKey,
		&i.PngKey,
		&i.Artist,
		&i.Credit,
		&i.FailureStage,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPosterJob = `-- name: GetPosterJob :one
SELECT id, performer, venue, date, status, svg_key, png_key, artist, credit, failure_stage, failure_reason, created_at, updated_at FROM poster_jobs WHERE id = $1
`

func (q *Queries) GetPosterJob(ctx context.Context, id string) (PosterJob, error) {
	row := q.db.QueryRow(ctx, getPosterJob, id)
	var i PosterJob
	err := row.Scan(
		&i.ID,
		&i.Performer,
		&i.Venue,
		&i.Date,
		&i.Status,
		&i.SvgKey,
		&i.PngKey,
		&i.Artist,
		&i.Credit,
		&i.FailureStage,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPosterJobFailed = `-- name: MarkPosterJobFailed :exec
UPDATE poster_jobs
SET status = 'failed', failure_stage = $2, failure_reason = $3, updated_at = NOW()
WHERE id = $1
`

type MarkPosterJobFailedParams struct {
	ID            string  `json:"id"`
	FailureStage  *string `json:"failure_stage"`
	FailureReason *string `json:"failure_reason"`
}

func (q *Queries) MarkPosterJobFailed(ctx context.Context, arg MarkPosterJobFailedParams) error {
	_, err := q.db.Exec(ctx, markPosterJobFailed, arg.ID, arg.FailureStage, arg.FailureReason)
	return err
}

const markPosterJobReady = `-- name: MarkPosterJobReady :exec
UPDATE poster_jobs
SET status = 'ready', svg_key = $2, png_key = $3, artist = $4, credit = $5,
    failure_stage = NULL, failure_reason = NULL, updated_at = NOW()
WHERE id = $1
`

type MarkPosterJobReadyParams struct {
	ID     string  `json:"id"`
	SvgKey *string `json:"svg_key"`
	PngKey *string `json:"png_key"`
	Artist []byte  `json:"artist"`
	Credit []byte  `json:"credit"`
}

func (q *Queries) MarkPosterJobReady(ctx context.Context, arg MarkPosterJobReadyParams) error {
	_, err := q.db.Exec(ctx, markPosterJobReady,
		arg.ID,
		arg.SvgKey,
		arg.PngKey,
		arg.Artist,
		arg.Credit,
	)
	return err
}
