// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limit.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRateLimitEvents = `-- name: CountRateLimitEvents :one
SELECT COUNT(*)
FROM rate_limit_events
WHERE bucket = $1
  AND key = $2
  AND created_at > $3
`

type CountRateLimitEventsParams struct {
	Bucket string             `json:"bucket"`
	Key    string             `json:"key"`
	Since  pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountRateLimitEvents(ctx context.Context, arg CountRateLimitEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRateLimitEvents, arg.Bucket, arg.Key, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRateLimitEventsBefore = `-- name: DeleteRateLimitEventsBefore :exec
DELETE FROM rate_limit_events
WHERE created_at < $1
`

func (q *Queries) DeleteRateLimitEventsBefore(ctx context.Context, before pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteRateLimitEventsBefore, before)
	return err
}

const insertRateLimitEvent = `-- name: InsertRateLimitEvent :exec
INSERT INTO rate_limit_events (bucket, key, created_at)
VALUES ($1, $2, $3)
`

type InsertRateLimitEventParams struct {
	Bucket    string             `json:"bucket"`
	Key       string             `json:"key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertRateLimitEvent(ctx context.Context, arg InsertRateLimitEventParams) error {
	_, err := q.db.Exec(ctx, insertRateLimitEvent, arg.Bucket, arg.Key, arg.CreatedAt)
	return err
}

const oldestRateLimitEvent = `-- name: OldestRateLimitEvent :one
SELECT created_at
FROM rate_limit_events
WHERE bucket = $1
  AND key = $2
  AND created_at > $3
ORDER BY created_at ASC
LIMIT 1
`

type OldestRateLimitEventParams struct {
	Bucket string             `json:"bucket"`
	Key    string             `json:"key"`
	Since  pgtype.Timestamptz `json:"since"`
}

func (q *Queries) OldestRateLimitEvent(ctx context.Context, arg OldestRateLimitEventParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, oldestRateLimitEvent, arg.Bucket, arg.Key, arg.Since)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}
