// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const searchEvents = `-- name: SearchEvents :many
WITH candidates AS (
        SELECT e.id,
               similarity(immutable_unaccent(e.title),
                          immutable_unaccent($3::text)) AS score
        FROM events e
        WHERE immutable_unaccent(e.title) % immutable_unaccent($3::text)
    UNION ALL
        -- 0.9: a performer match is nearly as good as a title match, and often
        -- IS the title match seen from the other side.
        SELECT p.event_id,
               similarity(immutable_unaccent(p.performer_name),
                          immutable_unaccent($3::text)) * 0.9
        FROM event_performers p
        WHERE immutable_unaccent(p.performer_name) % immutable_unaccent($3::text)
    UNION ALL
        -- 0.6: "Showbox" should surface shows at the Showbox, but must never
        -- outrank an artist of that name. Every event at a matched venue gets
        -- this score, so without the discount one venue hit floods the page.
        SELECT e.id,
               similarity(immutable_unaccent(v.name),
                          immutable_unaccent($3::text)) * 0.6
        FROM venues v
        JOIN events e ON e.venue_id = v.id
        WHERE immutable_unaccent(v.name) % immutable_unaccent($3::text)
),
best AS (SELECT id, max(score) AS rank FROM candidates GROUP BY id)
SELECT e.id, e.title, e.starts_at, e.image_url, e.segment,
       v.name AS venue_name, b.rank::float8 AS rank
FROM best b
JOIN events e ON e.id = b.id
JOIN venues v ON v.id = e.venue_id
WHERE v.city_id = $1
  AND e.archived_at IS NULL
  -- Same showable predicate as GetCityCalendarPage. Written after candidate
  -- generation because that is where it reads clearly; it is not a claim about
  -- the plan. event_over_at() is not indexed, and at dev scale the planner
  -- seq-scans rather than probing the trigram indexes first, so treat this as
  -- a correctness filter and re-measure before relying on it being cheap.
  AND event_over_at(e.starts_at, e.ends_at, e.time_tbd) > NOW()
ORDER BY b.rank DESC, e.starts_at ASC, e.id ASC
LIMIT $2
`

type SearchEventsParams struct {
	CityID      pgtype.UUID `json:"city_id"`
	ResultLimit int32       `json:"result_limit"`
	Query       string      `json:"query"`
}

type SearchEventsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	ImageUrl  *string            `json:"image_url"`
	Segment   *string            `json:"segment"`
	VenueName string             `json:"venue_name"`
	Rank      float64            `json:"rank"`
}

// Three legs unioned, then max()-ed per event: an event whose title AND
// performer both match scores as its best leg, not the sum, so a title hit is
// never outranked by an event matching weakly on two fields.
// ::float8 on rank: the three legs' scores are real vs. double precision (the
// 0.9/0.6 weighting promotes them), so sqlc can't statically resolve one type
// across the UNION and falls back to `any`. The cast is a no-op at runtime --
// Postgres already returns double precision here -- it only pins the type sqlc
// generates (float64) so callers don't need a type assertion.
// e.id last so the order is total: two events tied on rank and starts_at would
// otherwise come back in arbitrary order and flicker between keystrokes.
func (q *Queries) SearchEvents(ctx context.Context, arg SearchEventsParams) ([]SearchEventsRow, error) {
	rows, err := q.db.Query(ctx, searchEvents, arg.CityID, arg.ResultLimit, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEventsRow{}
	for rows.Next() {
		var i SearchEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartsAt,
			&i.ImageUrl,
			&i.Segment,
			&i.VenueName,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEventsSemantic = `-- name: SearchEventsSemantic :many
SELECT e.id, e.title, e.starts_at, e.image_url, e.segment,
       v.name AS venue_name
FROM events e
JOIN venues v ON v.id = e.venue_id
WHERE v.city_id = $1
  AND e.archived_at IS NULL
  AND e.embedding IS NOT NULL
  AND event_over_at(e.starts_at, e.ends_at, e.time_tbd) > NOW()
ORDER BY e.embedding <=> $2, e.id ASC
LIMIT $3
`

type SearchEventsSemanticParams struct {
	CityID         pgtype.UUID      `json:"city_id"`
	QueryEmbedding *pgvector.Vector `json:"query_embedding"`
	CandidateLimit int32            `json:"candidate_limit"`
}

type SearchEventsSemanticRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	ImageUrl  *string            `json:"image_url"`
	Segment   *string            `json:"segment"`
	VenueName string             `json:"venue_name"`
}

// The semantic leg, used only when SEARCH_SEMANTIC_ENABLED is on. Brute-force
// cosine over the live rows: 4.45ms at 10k events, so no ivfflat/hnsw index is
// warranted yet -- and adding one would trade exact results for approximate
// ones to save time we are not short of.
//
// Projects exactly the same display columns as SearchEvents, and deliberately
// so. RRF fuses the two legs' ORDERINGS, so a fused id may have come from this
// leg alone -- the "baseball" case in the design doc, where no event contains
// the string and every hit is semantic. When this query returned bare ids the
// handler had no display data for such a row and dropped it, which made the
// whole semantic leg unreachable: a query with no lexical rows returned an
// empty list, exactly as if the flag were off. Carrying the columns here costs
// nothing (the rows are already being read) and is what lets any fused id
// render. Do not reduce this back to `SELECT e.id`.
//
// What still deliberately does NOT leave SQL is the distance. The handler
// fuses by RANK, never by score -- see the Fusion note in the design for why
// no cosine cutoff can work -- so no similarity or distance column is
// projected from either leg.
// e.id ASC so the order is total. Ties are the common case, not an edge
// case: recurring events feed BuildEventText identical input and so get
// byte-identical embeddings -- 80 of the 195 embedded events in the dev
// catalogue fall into 26 such groups. Without the tiebreak both the order
// WITHIN a group and which of its rows survive LIMIT are unpinned, and
// ingestion re-upserts constantly, so the answer can change between
// keystrokes -- the same flicker the lexical leg's e.id ASC prevents.
func (q *Queries) SearchEventsSemantic(ctx context.Context, arg SearchEventsSemanticParams) ([]SearchEventsSemanticRow, error) {
	rows, err := q.db.Query(ctx, searchEventsSemantic, arg.CityID, arg.QueryEmbedding, arg.CandidateLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEventsSemanticRow{}
	for rows.Next() {
		var i SearchEventsSemanticRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartsAt,
			&i.ImageUrl,
			&i.Segment,
			&i.VenueName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
