// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, city_id)
VALUES ($1, $2, $3)
RETURNING id, email, city_id, created_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	CityID       pgtype.UUID `json:"city_id"`
}

type CreateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CityID    pgtype.UUID        `json:"city_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.CityID)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CityID,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultCity = `-- name: GetDefaultCity :one
SELECT id, slug, name, timezone
FROM cities
WHERE slug = 'v1-city'
`

func (q *Queries) GetDefaultCity(ctx context.Context) (City, error) {
	row := q.db.QueryRow(ctx, getDefaultCity)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, city_id, created_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CityID       pgtype.UUID        `json:"city_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CityID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, city_id, created_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CityID    pgtype.UUID        `json:"city_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CityID,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveUsersForMatching = `-- name: ListActiveUsersForMatching :many
SELECT id, interest_embedding
FROM users
WHERE deleted_at IS NULL
`

type ListActiveUsersForMatchingRow struct {
	ID                pgtype.UUID      `json:"id"`
	InterestEmbedding *pgvector.Vector `json:"interest_embedding"`
}

func (q *Queries) ListActiveUsersForMatching(ctx context.Context) ([]ListActiveUsersForMatchingRow, error) {
	rows, err := q.db.Query(ctx, listActiveUsersForMatching)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUsersForMatchingRow{}
	for rows.Next() {
		var i ListActiveUsersForMatchingRow
		if err := rows.Scan(&i.ID, &i.InterestEmbedding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUsersNeedingEmbedding = `-- name: SelectUsersNeedingEmbedding :many
SELECT u.id
FROM users u
WHERE u.deleted_at IS NULL
  AND (
    u.interest_embedding IS NULL
    OR u.interest_embedding_updated_at IS NULL
    OR u.interest_embedding_updated_at < COALESCE(
         (SELECT MAX(updated_at) FROM user_interests ui WHERE ui.user_id = u.id),
         u.created_at
       )
  )
`

func (q *Queries) SelectUsersNeedingEmbedding(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, selectUsersNeedingEmbedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserInterestEmbedding = `-- name: UpdateUserInterestEmbedding :exec
UPDATE users
SET interest_embedding = $2, interest_embedding_updated_at = NOW()
WHERE id = $1
`

type UpdateUserInterestEmbeddingParams struct {
	ID                pgtype.UUID      `json:"id"`
	InterestEmbedding *pgvector.Vector `json:"interest_embedding"`
}

func (q *Queries) UpdateUserInterestEmbedding(ctx context.Context, arg UpdateUserInterestEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateUserInterestEmbedding, arg.ID, arg.InterestEmbedding)
	return err
}
