// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_event_match.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteObsoleteMatches = `-- name: DeleteObsoleteMatches :exec
DELETE FROM user_event_match
WHERE event_id IN (
    SELECT id FROM events
    WHERE archived_at IS NOT NULL OR starts_at <= NOW()
)
`

func (q *Queries) DeleteObsoleteMatches(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteObsoleteMatches)
	return err
}

const deleteStaleMatchesForUsers = `-- name: DeleteStaleMatchesForUsers :exec
DELETE FROM user_event_match
WHERE user_id = ANY($1::uuid[])
  AND computed_at < $2
`

type DeleteStaleMatchesForUsersParams struct {
	UserIds []pgtype.UUID      `json:"user_ids"`
	Cutoff  pgtype.Timestamptz `json:"cutoff"`
}

func (q *Queries) DeleteStaleMatchesForUsers(ctx context.Context, arg DeleteStaleMatchesForUsersParams) error {
	_, err := q.db.Exec(ctx, deleteStaleMatchesForUsers, arg.UserIds, arg.Cutoff)
	return err
}

const upsertUserEventMatch = `-- name: UpsertUserEventMatch :exec
INSERT INTO user_event_match (user_id, event_id, score, score_breakdown, computed_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, event_id) DO UPDATE SET
    score           = EXCLUDED.score,
    score_breakdown = EXCLUDED.score_breakdown,
    computed_at     = EXCLUDED.computed_at
`

type UpsertUserEventMatchParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	EventID        pgtype.UUID        `json:"event_id"`
	Score          float64            `json:"score"`
	ScoreBreakdown []byte             `json:"score_breakdown"`
	ComputedAt     pgtype.Timestamptz `json:"computed_at"`
}

func (q *Queries) UpsertUserEventMatch(ctx context.Context, arg UpsertUserEventMatchParams) error {
	_, err := q.db.Exec(ctx, upsertUserEventMatch,
		arg.UserID,
		arg.EventID,
		arg.Score,
		arg.ScoreBreakdown,
		arg.ComputedAt,
	)
	return err
}
