// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_interests.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createManualInterest = `-- name: CreateManualInterest :one
INSERT INTO user_interests (user_id, kind, value, normalized_value, weight)
VALUES ($1, 'manual_tag', $2, $3, 1.0)
RETURNING id, value, normalized_value, weight, created_at
`

type CreateManualInterestParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	Value           string      `json:"value"`
	NormalizedValue string      `json:"normalized_value"`
}

type CreateManualInterestRow struct {
	ID              pgtype.UUID        `json:"id"`
	Value           string             `json:"value"`
	NormalizedValue string             `json:"normalized_value"`
	Weight          float64            `json:"weight"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateManualInterest(ctx context.Context, arg CreateManualInterestParams) (CreateManualInterestRow, error) {
	row := q.db.QueryRow(ctx, createManualInterest, arg.UserID, arg.Value, arg.NormalizedValue)
	var i CreateManualInterestRow
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.NormalizedValue,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInterestByIDForUser = `-- name: DeleteInterestByIDForUser :exec
DELETE FROM user_interests
WHERE id = $1 AND user_id = $2
`

type DeleteInterestByIDForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteInterestByIDForUser(ctx context.Context, arg DeleteInterestByIDForUserParams) error {
	_, err := q.db.Exec(ctx, deleteInterestByIDForUser, arg.ID, arg.UserID)
	return err
}

const listManualInterestsByUser = `-- name: ListManualInterestsByUser :many
SELECT id, value, normalized_value, weight, created_at
FROM user_interests
WHERE user_id = $1 AND kind = 'manual_tag'
ORDER BY created_at ASC
`

type ListManualInterestsByUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	Value           string             `json:"value"`
	NormalizedValue string             `json:"normalized_value"`
	Weight          float64            `json:"weight"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListManualInterestsByUser(ctx context.Context, userID pgtype.UUID) ([]ListManualInterestsByUserRow, error) {
	rows, err := q.db.Query(ctx, listManualInterestsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManualInterestsByUserRow{}
	for rows.Next() {
		var i ListManualInterestsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.NormalizedValue,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
