// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_spotify_tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSpotifyDerivedInterests = `-- name: DeleteSpotifyDerivedInterests :exec
DELETE FROM user_interests
WHERE user_id = $1 AND kind IN ('spotify_top_artist', 'spotify_top_genre')
`

func (q *Queries) DeleteSpotifyDerivedInterests(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpotifyDerivedInterests, userID)
	return err
}

const deleteUserSpotifyTokens = `-- name: DeleteUserSpotifyTokens :exec
DELETE FROM user_spotify_tokens WHERE user_id = $1
`

func (q *Queries) DeleteUserSpotifyTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSpotifyTokens, userID)
	return err
}

const getUserSpotifyTokens = `-- name: GetUserSpotifyTokens :one
SELECT user_id, access_token_enc, refresh_token_enc, expires_at, scope, last_synced_at
FROM user_spotify_tokens
WHERE user_id = $1
`

type GetUserSpotifyTokensRow struct {
	UserID          pgtype.UUID        `json:"user_id"`
	AccessTokenEnc  []byte             `json:"access_token_enc"`
	RefreshTokenEnc []byte             `json:"refresh_token_enc"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Scope           string             `json:"scope"`
	LastSyncedAt    pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) GetUserSpotifyTokens(ctx context.Context, userID pgtype.UUID) (GetUserSpotifyTokensRow, error) {
	row := q.db.QueryRow(ctx, getUserSpotifyTokens, userID)
	var i GetUserSpotifyTokensRow
	err := row.Scan(
		&i.UserID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.ExpiresAt,
		&i.Scope,
		&i.LastSyncedAt,
	)
	return i, err
}

const insertSpotifyInterest = `-- name: InsertSpotifyInterest :exec
INSERT INTO user_interests (user_id, kind, value, normalized_value, weight)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, kind, normalized_value) DO UPDATE SET
    value      = EXCLUDED.value,
    weight     = EXCLUDED.weight,
    updated_at = NOW()
`

type InsertSpotifyInterestParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	Kind            string      `json:"kind"`
	Value           string      `json:"value"`
	NormalizedValue string      `json:"normalized_value"`
	Weight          float64     `json:"weight"`
}

func (q *Queries) InsertSpotifyInterest(ctx context.Context, arg InsertSpotifyInterestParams) error {
	_, err := q.db.Exec(ctx, insertSpotifyInterest,
		arg.UserID,
		arg.Kind,
		arg.Value,
		arg.NormalizedValue,
		arg.Weight,
	)
	return err
}

const listUserSpotifyTokens = `-- name: ListUserSpotifyTokens :many
SELECT user_id, access_token_enc, refresh_token_enc, expires_at, scope, last_synced_at
FROM user_spotify_tokens
ORDER BY user_id ASC
`

type ListUserSpotifyTokensRow struct {
	UserID          pgtype.UUID        `json:"user_id"`
	AccessTokenEnc  []byte             `json:"access_token_enc"`
	RefreshTokenEnc []byte             `json:"refresh_token_enc"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Scope           string             `json:"scope"`
	LastSyncedAt    pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) ListUserSpotifyTokens(ctx context.Context) ([]ListUserSpotifyTokensRow, error) {
	rows, err := q.db.Query(ctx, listUserSpotifyTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSpotifyTokensRow{}
	for rows.Next() {
		var i ListUserSpotifyTokensRow
		if err := rows.Scan(
			&i.UserID,
			&i.AccessTokenEnc,
			&i.RefreshTokenEnc,
			&i.ExpiresAt,
			&i.Scope,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceSpotifyArtistInterests = `-- name: ReplaceSpotifyArtistInterests :exec
DELETE FROM user_interests
WHERE user_id = $1 AND kind = 'spotify_top_artist'
`

func (q *Queries) ReplaceSpotifyArtistInterests(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceSpotifyArtistInterests, userID)
	return err
}

const replaceSpotifyGenreInterests = `-- name: ReplaceSpotifyGenreInterests :exec
DELETE FROM user_interests
WHERE user_id = $1 AND kind = 'spotify_top_genre'
`

func (q *Queries) ReplaceSpotifyGenreInterests(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceSpotifyGenreInterests, userID)
	return err
}

const updateUserSpotifyTokensLastSynced = `-- name: UpdateUserSpotifyTokensLastSynced :exec
UPDATE user_spotify_tokens
SET last_synced_at = NOW(), updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) UpdateUserSpotifyTokensLastSynced(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserSpotifyTokensLastSynced, userID)
	return err
}

const upsertUserSpotifyTokens = `-- name: UpsertUserSpotifyTokens :exec
INSERT INTO user_spotify_tokens (
    user_id, access_token_enc, refresh_token_enc, expires_at, scope
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id)
DO UPDATE SET
    access_token_enc  = EXCLUDED.access_token_enc,
    refresh_token_enc = EXCLUDED.refresh_token_enc,
    expires_at        = EXCLUDED.expires_at,
    scope             = EXCLUDED.scope,
    updated_at        = NOW()
`

type UpsertUserSpotifyTokensParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	AccessTokenEnc  []byte             `json:"access_token_enc"`
	RefreshTokenEnc []byte             `json:"refresh_token_enc"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Scope           string             `json:"scope"`
}

func (q *Queries) UpsertUserSpotifyTokens(ctx context.Context, arg UpsertUserSpotifyTokensParams) error {
	_, err := q.db.Exec(ctx, upsertUserSpotifyTokens,
		arg.UserID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.ExpiresAt,
		arg.Scope,
	)
	return err
}
