// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venues.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertVenue = `-- name: UpsertVenue :one
INSERT INTO venues (city_id, name, normalized_name, address, lat, lng, website_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (city_id, normalized_name)
DO UPDATE SET
    name        = EXCLUDED.name,
    address     = EXCLUDED.address,
    lat         = EXCLUDED.lat,
    lng         = EXCLUDED.lng,
    website_url = EXCLUDED.website_url,
    updated_at  = NOW()
RETURNING id
`

type UpsertVenueParams struct {
	CityID         pgtype.UUID `json:"city_id"`
	Name           string      `json:"name"`
	NormalizedName string      `json:"normalized_name"`
	Address        *string     `json:"address"`
	Lat            *float64    `json:"lat"`
	Lng            *float64    `json:"lng"`
	WebsiteUrl     *string     `json:"website_url"`
}

func (q *Queries) UpsertVenue(ctx context.Context, arg UpsertVenueParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertVenue,
		arg.CityID,
		arg.Name,
		arg.NormalizedName,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.WebsiteUrl,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
