include classpath("application.conf")

node-address {
  protocol  = http
  host      = "*"
  port      = 9324
  context-path = ""
}

rest-sqs {
  enabled       = true
  bind-port     = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits    = strict
}

queues {
  events-queue {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait       = 20 seconds
    deadLettersQueue {
      name              = events-dlq
      maxReceiveCount   = 3
    }
  }
  events-dlq {}

  interests-queue {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait       = 20 seconds
    deadLettersQueue {
      name              = interests-dlq
      maxReceiveCount   = 3
    }
  }
  interests-dlq {}
}
